version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: photo_social_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/photo_social_db
      - PORT=3000

  client:
    image: tedecanela/client_photo:latest
    container_name: photo_social_client
    ports: 
      - "8081:8081"
    depends_on:
      - backend

volumes:
  mongo-data:
